version: '3.8'

services:
  app:
    build: .
    container_name: flask_server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app/backend/python
    environment:
      - FLASK_ENV=development
    command: python server.py
